// vardoger: raw syscall dispatcher.
//
// When the interrupt hook decides a trap is a real syscall (PC not on the
// trampoline page), it routes here. This is a HOST-side reimplementation of the
// Linux/Android kernel ABI: guest arm64/arm32 code issues an SVC and we service
// it on the mac/linux box the tool runs on, so the guest behaves as if it were
// on a real, un-rooted, un-debugged device.
//
// Coverage is complete: every syscall number on both ABIs (arm64 asm-generic +
// arm32 EABI, incl. the __ARM_NR_* private range) is mapped in
// syscall_table.inc to either a bespoke handler (mmap/mprotect -> Memory, file
// ops -> System/Vfs, a controlled clock, pid/uid, getrandom, ptrace, ...) or a
// faithful default return (advisory ops succeed; privileged ops that a sandboxed
// app can't do report -EPERM; sockets -EACCES; obscure ones -ENOSYS) -- so no
// syscall falls through unnamed or crashes the guest. The number->name/handler
// tables are generated by scripts/gen_syscall_table.py from the NDK headers.
#pragma once

#include <cstdint>
#include <functional>
#include <unordered_map>

#include "vardoger/android/system.hpp"
#include "vardoger/engine/engine.hpp"
#include "vardoger/engine/memory.hpp"

namespace vardoger {

class Syscalls {
 public:
  Syscalls(Engine& engine, Memory& mem, System& sys)
      : e_(engine), mem_(mem), sys_(sys) {}

  // Read the syscall number, run the handler, set the return register.
  void dispatch(Engine& e);

  // Observe every raw syscall the guest issues via SVC: fires
  // (nr, name, args[0..5], ret) after the handler runs, so an analyst can trace
  // the exact syscalls a packer makes (ptrace probes, getrandom, mprotect W^X
  // flips, openat of /proc, ...). `name` is a short mnemonic ("ptrace",
  // "openat", or "sys_<nr>" for numbers we pass through). One observer.
  using SyscallObserver = std::function<void(
      uint64_t nr, const char* name, const uint64_t args[6], uint64_t ret)>;
  void set_syscall_observer(SyscallObserver o) { observer_ = std::move(o); }

  // Cooperative-yield hook. nanosleep/sched_yield call this to give the CPU to
  // another thread, a real sleeping thread yields the scheduler. Without it, a
  // packer's watchdog thread (sleep -> poll -> maybe self-destruct) never lets
  // the main thread run, so it always sees "no progress" and self-destructs.
  // The hook should perform a scheduler yield (returning to the caller next
  // time) and return true; if no scheduler is active it returns false and the
  // caller just returns 0 (old behavior).
  void set_yield(std::function<bool()> y) { yield_ = std::move(y); }

  // Wire raw clone/clone3/fork/vfork into the cooperative scheduler: create a
  // child green-thread (a copy of the caller's CPU context that returns 0) and
  // hand the parent the child's tid. The callback receives the child stack top
  // (0 = share the parent's stack, fork/COW-style), the new TLS (0 = inherit),
  // the raw clone flags, and the CLONE_*_SETTID pointers (0 = none). It returns
  // the child tid on success, or 0 if it can't schedule one (no active
  // scheduler / not arm64), so the dispatcher falls back to -ENOSYS. Without a
  // hook, process/thread-creating syscalls report -ENOSYS. See Scheduler.
  using CloneFn =
      std::function<uint64_t(Engine& e, uint64_t child_sp, uint64_t tls,
                             uint64_t flags, uint64_t ptid, uint64_t ctid)>;
  void set_clone(CloneFn f) { clone_ = std::move(f); }

  // Route exit/exit_group into the scheduler so a terminating thread (notably a
  // raw-clone child, which ends by calling exit rather than returning) is reaped
  // and another thread runs, instead of stopping the whole VM. The callback gets
  // the exit status and returns true if it consumed the exit (scheduler active);
  // false -> the dispatcher stops the VM (the no-scheduler default).
  using ExitFn = std::function<bool(uint64_t status)>;
  void set_thread_exit(ExitFn f) { exit_ = std::move(f); }

 private:
  // Mint a fresh, VFS-backed fd for an "anonymous" object (eventfd/timerfd/
  // signalfd/inotify/epoll/memfd/pipe): a real read/write/close-able handle so a
  // guest that pokes the fd behaves, backed by a unique reserved path.
  int mint_fd(const char* tag);

  Engine& e_;
  Memory& mem_;
  System& sys_;  // single fd table lives here (shared with libc stubs)
  std::function<bool()> yield_;
  CloneFn clone_;
  ExitFn exit_;
  SyscallObserver observer_;
  uint64_t brk_cur_ = 0;  // emulated program break (lazily seeded on first brk)
  int anon_seq_ = 0;      // uniquifier for mint_fd() reserved paths
};

}  // namespace vardoger
